# Generated by Django 4.2.13 on 2024-05-12 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outfit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField(default=1000)),
                ("image", models.ImageField(upload_to="outfits/")),
                ("thumbnail", models.ImageField(upload_to="outfits/thumbnails/")),
                ("ticketid", models.IntegerField(default=0)),
                ("stylist", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "outfit_table",
            },
        ),
    ]
