# Generated by Django 4.2.13 on 2024-05-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_item_itemid_alter_item_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="items",
            field=models.ManyToManyField(blank=True, to="studio.item"),
        ),
    ]
