# Generated by Django 4.2.13 on 2024-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_outfit_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="image",
            field=models.ImageField(default="outfits/default_img.jpg", upload_to="uploads/"),
        ),
    ]
