# Generated by Django 4.2.13 on 2024-05-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_outfit_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="thumbnail",
        ),
    ]
