# Generated by Django 4.2.13 on 2024-05-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_remove_outfit_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="stylist",
        ),
        migrations.AddField(
            model_name="outfit",
            name="maker_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
