# Generated by Django 4.2.13 on 2024-05-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0011_alter_ticket_style2"),
        ("core", "0006_remove_outfit_stylist_outfit_maker_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="ticketid",
        ),
        migrations.AddField(
            model_name="outfit",
            name="ticket_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="box.ticket"
            ),
        ),
    ]
