# Generated by Django 4.2.13 on 2024-05-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_remove_outfit_ticketid_outfit_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="maker_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
