# Generated by Django 4.2.13 on 2024-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_outfit_maker_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="portrait",
            field=models.ImageField(default="portraits/default_img.jpg", upload_to="portraits/"),
        ),
    ]
