# Generated by Django 4.2.13 on 2024-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_outfit_portrait"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
