# Generated by Django 4.2.13 on 2024-06-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_outfit_hidden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outfit",
            name="hidden",
        ),
    ]
