# Generated by Django 4.2.13 on 2024-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_outfit_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="portrait",
            field=models.ImageField(blank=True, default="portraits/default_img.jpg", null=True, upload_to="portraits/"),
        ),
    ]
