# Generated by Django 4.2.13 on 2024-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_outfit_portrait"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="maker_grid_visibility",
            field=models.CharField(
                blank=True, choices=[("show", "Show"), ("hide", "Side")], default="show", max_length=10, null=True
            ),
        ),
    ]
