# Generated by Django 4.2.13 on 2024-07-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_outfit_maker_grid_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outfit",
            name="maker_grid_visibility",
            field=models.CharField(
                blank=True, choices=[("show", "Show"), ("hide", "Hide")], default="show", max_length=10, null=True
            ),
        ),
    ]
