# Generated by Django 4.2.13 on 2024-05-12 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("style1", models.CharField(max_length=100)),
                ("style2", models.CharField(max_length=100)),
                ("occasion", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("notpaid", "notpaid"), ("open", "open"), ("closed", "closed"), ("boxed", "boxed")],
                        default="notpaid",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("customer", models.CharField(default="guest", max_length=100)),
                ("outfit1", models.CharField(blank=True, default="", max_length=100)),
                ("outfit2", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
