# Generated by Django 4.2.13 on 2024-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="max_outfits",
            field=models.IntegerField(default=5),
        ),
    ]
