# Generated by Django 4.2.13 on 2024-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_ticket_max_outfits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="max_outfits",
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_outfits",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="ticket",
            name="maximum_outfits",
            field=models.IntegerField(default=5),
        ),
    ]
