# Generated by Django 4.2.13 on 2024-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0003_remove_ticket_max_outfits_ticket_current_outfits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="current_outfits",
            field=models.IntegerField(default=0),
        ),
    ]
