# Generated by Django 4.2.13 on 2024-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_outfit_items"),
        ("box", "0004_alter_ticket_current_outfits"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="outfits_all",
            field=models.ManyToManyField(blank=True, to="core.outfit"),
        ),
    ]
