# Generated by Django 4.2.13 on 2024-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0005_ticket_outfits_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="stylists_all",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
