# Generated by Django 4.2.13 on 2024-05-12 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0006_ticket_stylists_all"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="stylists_all",
        ),
        migrations.AddField(
            model_name="ticket",
            name="stylists_all",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
