# Generated by Django 4.2.13 on 2024-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0007_remove_ticket_stylists_all_ticket_stylists_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="size_bottom_xyz",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="size_shoe_eu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="size_top_xyz",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="size_waist_inches",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
