# Generated by Django 4.2.13 on 2024-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_alter_item_itemid"),
        ("box", "0008_ticket_size_bottom_xyz_ticket_size_shoe_eu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.CharField(blank=True, max_length=30, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=30, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("money", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("preparing", "preparing"), ("shipped", "shipped"), ("delivered", "delivered")],
                        max_length=10,
                    ),
                ),
                ("address_customer", models.CharField(blank=True, max_length=100, null=True)),
                ("address_fumio", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("box", "box"), ("item", "item")], max_length=5)),
                ("ticket_id", models.CharField(max_length=30)),
                ("money", models.FloatField(blank=True, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("preparing", "preparing"), ("shipped", "shipped"), ("delivered", "delivered")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address_customer", models.CharField(blank=True, max_length=100, null=True)),
                ("address_fumio", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                ("items", models.ManyToManyField(to="studio.item")),
            ],
        ),
    ]
