# Generated by Django 4.2.13 on 2024-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0009_return_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="customer",
            field=models.CharField(default="guest", max_length=100, null=True),
        ),
    ]
