# Generated by Django 4.2.13 on 2024-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0010_alter_ticket_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="style2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
