# Generated by Django 4.2.13 on 2024-05-30 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0011_alter_ticket_style2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="customer",
        ),
        migrations.AddField(
            model_name="ticket",
            name="creator_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
