# Generated by Django 4.2.13 on 2024-05-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0012_remove_ticket_customer_ticket_creator_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ticket_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="box.ticket"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="creator_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="stylists_all",
            field=models.ManyToManyField(blank=True, related_name="stylist_tickets", to=settings.AUTH_USER_MODEL),
        ),
    ]
