# Generated by Django 4.2.13 on 2024-05-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0013_alter_order_ticket_id_alter_ticket_creator_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="order",
            name="creator_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
