# Generated by Django 4.2.13 on 2024-05-30 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0014_remove_order_customer_id_order_creator_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="return",
            name="creator_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="order_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="box.order"
            ),
        ),
    ]
