# Generated by Django 4.2.13 on 2024-05-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0015_remove_return_customer_id_return_creator_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="creator_id",
        ),
        migrations.AddField(
            model_name="return",
            name="returner_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
