# Generated by Django 4.2.13 on 2024-06-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_outfit_portrait"),
        ("box", "0016_remove_return_creator_id_return_returner_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="outfit1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_outfit1",
                to="core.outfit",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="outfit2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_outfit2",
                to="core.outfit",
            ),
        ),
    ]
