# Generated by Django 4.2.13 on 2024-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0017_alter_ticket_outfit1_alter_ticket_outfit2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="size_shoe_eu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("34", "34"),
                    ("35", "35"),
                    ("36", "36"),
                    ("37", "37"),
                    ("38", "38"),
                    ("39", "39"),
                    ("40", "40"),
                    ("41", "41"),
                    ("42", "42"),
                    ("43", "43"),
                    ("44", "44"),
                    ("45", "45"),
                    ("46", "46"),
                    ("47", "47"),
                    ("48", "48"),
                    ("34.5", "34.5"),
                    ("35.5", "35.5"),
                    ("36.5", "36.5"),
                    ("37.5", "37.5"),
                    ("38.5", "38.5"),
                    ("39.5", "39.5"),
                    ("40.5", "40.5"),
                    ("41.5", "41.5"),
                    ("42.5", "42.5"),
                    ("43.5", "43.5"),
                    ("44.5", "44.5"),
                    ("45.5", "45.5"),
                    ("46.5", "46.5"),
                    ("47.5", "47.5"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
