# Generated by Django 4.2.13 on 2024-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0018_alter_ticket_size_shoe_eu"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="size_shoe_uk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("2.5", "2.5"),
                    ("3.5", "3.5"),
                    ("4.5", "4.5"),
                    ("5.5", "5.5"),
                    ("6.5", "6.5"),
                    ("7.5", "7.5"),
                    ("8.5", "8.5"),
                    ("9.5", "9.5"),
                    ("10.5", "10.5"),
                    ("11.5", "11.5"),
                    ("12.5", "12.5"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="size_waist_inches",
            field=models.CharField(
                blank=True,
                choices=[
                    ("24", "24"),
                    ("25", "25"),
                    ("26", "26"),
                    ("27", "27"),
                    ("28", "28"),
                    ("29", "29"),
                    ("30", "30"),
                    ("31", "31"),
                    ("32", "32"),
                    ("33", "33"),
                    ("34", "34"),
                    ("35", "35"),
                    ("36", "36"),
                    ("37", "37"),
                    ("38", "38"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
