# Generated by Django 4.2.13 on 2024-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0019_ticket_size_shoe_uk_alter_ticket_size_waist_inches"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="colortype",
            field=models.CharField(choices=[("white", "white"), ("golden", "golden")], default="white", max_length=10),
        ),
    ]
