# Generated by Django 4.2.13 on 2024-06-16 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_style"),
        ("box", "0020_ticket_colortype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="style2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style2_tickets",
                to="studio.style",
            ),
        ),
    ]
