# Generated by Django 4.2.13 on 2024-06-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_style"),
        ("box", "0022_remove_ticket_style1"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="style1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style1_tickets",
                to="studio.style",
            ),
        ),
    ]
