# Generated by Django 4.2.13 on 2024-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0023_ticket_style1"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.CharField(
                choices=[("styled_outfits", "styled outfits"), ("liked_items", "liked items")],
                default="styled_outfits",
                max_length=30,
            ),
        ),
    ]
