# Generated by Django 4.2.13 on 2024-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0024_ticket_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="occasion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
