# Generated by Django 4.2.13 on 2024-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0025_alter_ticket_occasion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="colortype",
        ),
    ]
