# Generated by Django 4.2.13 on 2024-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0027_ticket_filter_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="asktype",
            field=models.CharField(choices=[("fit", "fit"), ("box", "box")], default="fit", max_length=30),
        ),
    ]
