# Generated by Django 4.2.13 on 2024-06-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0028_ticket_asktype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="condition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
