# Generated by Django 4.2.13 on 2024-07-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0029_alter_ticket_condition_alter_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="creator_profile_visibility",
            field=models.CharField(
                blank=True, choices=[("show", "Show"), ("hide", "Hide")], default="show", max_length=10, null=True
            ),
        ),
    ]
