# Generated by Django 4.2.13 on 2024-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0030_ticket_creator_profile_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="asktype",
            field=models.CharField(choices=[("outfit", "outfit"), ("box", "box")], default="fit", max_length=30),
        ),
    ]
