# Generated by Django 4.2.13 on 2024-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0031_alter_ticket_asktype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="asktype",
            field=models.CharField(choices=[("outfit", "outfit"), ("box", "box")], default="outfit", max_length=30),
        ),
    ]
