# Generated by Django 4.2.13 on 2024-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0032_alter_ticket_asktype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="filter_liked",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="type",
        ),
        migrations.AddField(
            model_name="ticket",
            name="catalogue",
            field=models.CharField(
                choices=[("full_catalogue", "full catalogue"), ("liked_only", "liked only")],
                default="full_catalogue",
                max_length=30,
            ),
        ),
    ]
