# Generated by Django 4.2.13 on 2024-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0033_remove_ticket_filter_liked_remove_ticket_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="catalogue",
            field=models.CharField(
                choices=[("all_items", "all items"), ("liked_only", "liked only")], default="all_items", max_length=30
            ),
        ),
    ]
