# Generated by Django 4.2.13 on 2024-08-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0034_alter_ticket_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="boxcuratedby",
            field=models.CharField(
                choices=[("human_stylist", "human stylist"), ("personalized_algorithm", "personalized algorithm")],
                default="human_stylist",
                max_length=30,
            ),
        ),
    ]
