# Generated by Django 4.2.13 on 2025-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0035_ticket_boxcuratedby"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="stylist_type",
            field=models.CharField(
                blank=True,
                choices=[("everyone", "Everyone"), ("following", "Following")],
                default="everyone",
                max_length=25,
                null=True,
            ),
        ),
    ]
