# Generated by Django 4.2.13 on 2025-06-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0037_alter_ticket_stylist_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="private_stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_stylist_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
