# Generated by Django 4.2.13 on 2024-05-12 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag_name", models.CharField(blank=True, max_length=100)),
                ("tag_type", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, default="nologo", max_length=100)),
                (
                    "condition",
                    models.CharField(blank=True, choices=[("new", "new"), ("pre-owned", "pre-owned")], max_length=10),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_ship_ready", models.CharField(blank=True, choices=[("yes", "yes"), ("no", "no")], max_length=3)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="studio.tag")),
            ],
        ),
    ]
