# Generated by Django 4.2.13 on 2024-05-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default="items/default.jpg", upload_to="items/"),
        ),
    ]
