# Generated by Django 4.2.13 on 2024-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_item_itemid_alter_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cat",
            field=models.CharField(
                blank=True,
                choices=[("top", "top"), ("bottom", "bottom"), ("accessory", "accessory"), ("footwear", "footwear")],
                max_length=20,
            ),
        ),
    ]
