# Generated by Django 4.2.13 on 2024-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_item_cat"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioOutfitTemp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item1img",
                    models.ImageField(default="studiooutfittemps/default_img1.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item1id", models.CharField(max_length=20)),
                (
                    "item2img",
                    models.ImageField(default="studiooutfittemps/default_img2.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item2id", models.CharField(max_length=20)),
                (
                    "item3img",
                    models.ImageField(default="studiooutfittemps/default_img3.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item3id", models.CharField(max_length=20)),
                (
                    "item4img",
                    models.ImageField(default="studiooutfittemps/default_img4.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item4id", models.CharField(max_length=20)),
            ],
        ),
    ]
