# Generated by Django 4.2.13 on 2024-05-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_studiooutfittemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studiooutfittemp",
            name="item1id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studiooutfittemp",
            name="item2id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studiooutfittemp",
            name="item3id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studiooutfittemp",
            name="item4id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
