# Generated by Django 4.2.13 on 2024-05-12 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0007_remove_ticket_stylists_all_ticket_stylists_all"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0006_alter_studiooutfittemp_item1id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studiooutfittemp",
            name="ticket",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="box.ticket"
            ),
        ),
        migrations.AddField(
            model_name="studiooutfittemp",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
