# Generated by Django 4.2.13 on 2024-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0007_studiooutfittemp_ticket_studiooutfittemp_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
