# Generated by Django 4.2.13 on 2024-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0008_alter_item_name_remove_item_tags_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="shoe_mw",
            field=models.CharField(
                blank=True, choices=[("man", "man"), ("woman", "woman"), ("unisex", "unisex")], max_length=10
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="size_chest_inches",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size_eu",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size_uk",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size_us",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size_waist_inches",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size_xyz",
            field=models.CharField(
                blank=True, choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")], max_length=10
            ),
        ),
    ]
