# Generated by Django 4.2.13 on 2024-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0009_item_shoe_mw_item_size_chest_inches_item_size_eu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, default="nologo", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.CharField(
                blank=True, choices=[("new", "new"), ("pre-owned", "pre-owned")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, default="items/default.jpg", null=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_ship_ready",
            field=models.CharField(blank=True, choices=[("yes", "yes"), ("no", "no")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="shoe_mw",
            field=models.CharField(
                blank=True, choices=[("man", "man"), ("woman", "woman"), ("unisex", "unisex")], max_length=10, null=True
            ),
        ),
    ]
