# Generated by Django 4.2.13 on 2024-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0010_alter_item_brand_alter_item_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="itemid",
            field=models.CharField(max_length=30),
        ),
    ]
