# Generated by Django 4.2.13 on 2024-05-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0012_alter_item_itemid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
