# Generated by Django 4.2.13 on 2024-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0013_item_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sku",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="itemid",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
