# Generated by Django 4.2.13 on 2024-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0014_item_sku_alter_item_itemid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="taglist",
            field=models.ManyToManyField(blank=True, to="studio.tag"),
        ),
    ]
