# Generated by Django 4.2.13 on 2024-05-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0015_item_taglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
