# Generated by Django 4.2.13 on 2024-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0016_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="cat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("top", "top"),
                    ("bottom", "bottom"),
                    ("accessory", "accessory"),
                    ("footwear", "footwear"),
                    ("dress", "dress"),
                ],
                max_length=20,
            ),
        ),
    ]
