# Generated by Django 4.2.13 on 2024-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0017_alter_item_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="size_xyz",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=10,
                null=True,
            ),
        ),
    ]
