# Generated by Django 4.2.13 on 2024-06-10 03:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0018_alter_item_size_xyz"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_url", models.CharField(blank=True, max_length=255, null=True)),
                ("size_mapping", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
