# Generated by Django 4.2.13 on 2024-06-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0019_shopifystore"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="shopify_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="shopify_store",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="studio.shopifystore"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sizes_xyz",
            field=models.ManyToManyField(blank=True, to="studio.sizecategory"),
        ),
    ]
