# Generated by Django 4.2.13 on 2024-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0020_sizecategory_item_shopify_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopifystore",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
