# Generated by Django 4.2.13 on 2024-06-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0021_shopifystore_address_shopifystore_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_ship_ready",
        ),
        migrations.RemoveField(
            model_name="item",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="item",
            name="shoe_mw",
        ),
        migrations.RemoveField(
            model_name="item",
            name="size_chest_inches",
        ),
        migrations.RemoveField(
            model_name="item",
            name="size_us",
        ),
        migrations.RemoveField(
            model_name="item",
            name="size_xyz",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="item",
            name="stock",
        ),
    ]
