# Generated by Django 4.2.13 on 2024-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0022_remove_item_is_ship_ready_remove_item_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeShoeUkCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("2.5", "2.5"),
                            ("3", "3"),
                            ("3.5", "3.5"),
                            ("4", "4"),
                            ("4.5", "4.5"),
                            ("5", "5"),
                            ("5.5", "5.5"),
                            ("6", "6"),
                            ("6.5", "6.5"),
                            ("7", "7"),
                            ("7.5", "7.5"),
                            ("8", "8"),
                            ("8.5", "8.5"),
                            ("9", "9"),
                            ("9.5", "9.5"),
                            ("10", "10"),
                            ("10.5", "10.5"),
                            ("11", "11"),
                            ("11.5", "11.5"),
                            ("12", "12"),
                            ("12.5", "12.5"),
                            ("13", "13"),
                            ("13.5", "13.5"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
