# Generated by Django 4.2.13 on 2024-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0023_sizeshoeukcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeWaistInchCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                            ("32", "32"),
                            ("33", "33"),
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="sizes_shoe_uk",
            field=models.ManyToManyField(blank=True, to="studio.sizeshoeukcategory"),
        ),
    ]
