# Generated by Django 4.2.13 on 2024-06-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0024_sizewaistinchcategory_item_sizes_shoe_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sizes_waist_inches",
            field=models.ManyToManyField(blank=True, to="studio.sizewaistinchcategory"),
        ),
    ]
