# Generated by Django 4.2.13 on 2024-06-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0025_item_sizes_waist_inches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="size_uk",
        ),
        migrations.RemoveField(
            model_name="item",
            name="size_waist_inches",
        ),
    ]
