# Generated by Django 4.2.13 on 2024-06-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0026_remove_item_size_uk_remove_item_size_waist_inches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="size_eu",
        ),
    ]
