# Generated by Django 4.2.13 on 2024-06-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0027_remove_item_size_eu"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopifystore",
            name="address_city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="address_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="address_street_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="address_street_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="api_store_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shopifystore",
            name="store_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shopify", "Shopify"),
                    ("bigcommerce", "BigCommerce"),
                    ("woocommerce", "WooCommerce"),
                    ("magento", "Magento"),
                    ("squarespace", "Squarespace"),
                    ("wix", "Wix"),
                    ("prestashop", "PrestaShop"),
                    ("weebly", "Weebly"),
                    ("bigcartel", "BigCartel"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
