# Generated by Django 4.2.13 on 2024-06-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0028_shopifystore_address_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopifystore",
            name="address",
        ),
        migrations.RemoveField(
            model_name="shopifystore",
            name="location",
        ),
    ]
