# Generated by Django 4.2.13 on 2024-06-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0029_remove_shopifystore_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shopifystore",
            old_name="access_token",
            new_name="api_access_token",
        ),
        migrations.RenameField(
            model_name="shopifystore",
            old_name="store_platform",
            new_name="platform",
        ),
    ]
