# Generated by Django 4.2.13 on 2024-06-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0030_rename_access_token_shopifystore_api_access_token_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopifyStore",
            new_name="EcommerceStore",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="shopify_product_id",
            new_name="ecommerce_product_id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="shopify_store",
            new_name="ecommerce_store",
        ),
    ]
