# Generated by Django 4.2.13 on 2024-06-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0031_rename_shopifystore_ecommercestore_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="brand",
        ),
    ]
