# Generated by Django 4.2.13 on 2024-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0032_remove_item_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeShoeEuCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("34", "34"),
                            ("34.5", "34.5"),
                            ("35", "35"),
                            ("35.5", "35.5"),
                            ("36", "36"),
                            ("36.5", "36.5"),
                            ("37", "37"),
                            ("37.5", "37.5"),
                            ("38", "38"),
                            ("38.5", "38.5"),
                            ("39", "39"),
                            ("39.5", "39.5"),
                            ("40", "40"),
                            ("40.5", "40.5"),
                            ("41", "41"),
                            ("41.5", "41.5"),
                            ("42", "42"),
                            ("42.5", "42.5"),
                            ("43", "43"),
                            ("43.5", "43.5"),
                            ("44", "44"),
                            ("44.5", "44.5"),
                            ("45", "45"),
                            ("45.5", "45.5"),
                            ("46", "46"),
                            ("46.5", "46.5"),
                            ("47", "47"),
                            ("47.5", "47.5"),
                            ("48", "48"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="sizes_shoe_eu",
            field=models.ManyToManyField(blank=True, to="studio.sizeshoeeucategory"),
        ),
    ]
