# Generated by Django 4.2.13 on 2024-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="formtype",
            field=models.CharField(
                blank=True, choices=[("physical", "physical"), ("virtual", "virtual")], max_length=20
            ),
        ),
    ]
