# Generated by Django 4.2.13 on 2024-07-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0035_item_formtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="formtype",
            new_name="modality",
        ),
    ]
