# Generated by Django 4.2.13 on 2024-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0036_rename_formtype_item_modality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizecategory",
            name="name",
            field=models.CharField(
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL"), ("one_size", "One Size")],
                max_length=10,
                unique=True,
            ),
        ),
    ]
