# Generated by Django 4.2.13 on 2025-07-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0038_alter_ecommercestore_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="dummy",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
