# Generated by Django 4.2.13 on 2025-07-17 01:16

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0039_item_dummy"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
