# Generated by Django 4.2.13 on 2024-05-24 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0013_item_stock"),
        ("accounts", "0002_alter_customer_height_alter_customer_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_customer",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_seller",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=10),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("items_sold", models.IntegerField(blank=True, default=0, null=True)),
                ("items_boxed", models.IntegerField(blank=True, default=0, null=True)),
                ("total_sales", models.IntegerField(blank=True, default=0, null=True)),
                ("fumio_profit", models.IntegerField(blank=True, default=0, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("items", models.ManyToManyField(blank=True, to="studio.item")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
            },
        ),
    ]
