# Generated by Django 4.2.13 on 2024-05-24 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0016_item_price"),
        ("accounts", "0003_customuser_is_customer_customuser_is_seller_seller"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller",
            old_name="items",
            new_name="items_uploaded",
        ),
        migrations.RenameField(
            model_name="seller",
            old_name="items_boxed",
            new_name="seller_profit",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="location",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="timestamp",
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("items_sold", models.IntegerField(blank=True, default=0, null=True)),
                ("items_boxed", models.IntegerField(blank=True, default=0, null=True)),
                ("total_sales", models.IntegerField(blank=True, default=0, null=True)),
                ("fumio_profit", models.IntegerField(blank=True, default=0, null=True)),
                ("supplier_profit", models.IntegerField(blank=True, default=0, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("items_catalogue", models.ManyToManyField(blank=True, to="studio.item")),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
    ]
