# Generated by Django 4.2.13 on 2024-05-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_items_seller_items_uploaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
