# Generated by Django 4.2.13 on 2024-05-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_supplier_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="location",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
