# Generated by Django 4.2.13 on 2024-05-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_supplier_address_alter_supplier_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
