# Generated by Django 4.2.13 on 2024-05-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_supplier_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFollows",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user_from", "user_to")},
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="followers_list",
            field=models.ManyToManyField(
                related_name="following_list", through="accounts.UserFollows", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
