# Generated by Django 4.2.13 on 2024-05-29 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_bio_customuser_name_customuser_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pfp",
            field=models.ImageField(blank=True, default="pfps/default_img.jpg", null=True, upload_to="pfps/"),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userfollows",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
