# Generated by Django 4.2.13 on 2024-05-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_pfp_alter_userfollows_user_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={"verbose_name_plural": "UserFollows"},
        ),
    ]
