# Generated by Django 4.2.13 on 2024-06-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_portraitupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
