# Generated by Django 4.2.13 on 2024-06-13 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0021_shopifystore_address_shopifystore_location"),
        ("accounts", "0013_delete_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserItemLikes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clicker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicker_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studio.item")),
                (
                    "styler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styler_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Item Like",
                "verbose_name_plural": "User Item Likes",
                "db_table": "user_item_likes",
            },
        ),
    ]
