# Generated by Django 4.2.13 on 2024-06-13 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0021_shopifystore_address_shopifystore_location"),
        ("accounts", "0014_useritemlikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useritemlikes",
            name="clicker",
        ),
        migrations.AddField(
            model_name="useritemlikes",
            name="liker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liker_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useritemlikes",
            name="item",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="studio.item"
            ),
        ),
        migrations.AlterField(
            model_name="useritemlikes",
            name="styler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styler_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
