# Generated by Django 4.2.13 on 2024-06-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_useritemlikes_clicker_useritemlikes_liker_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useritemlikes",
            options={"verbose_name": "UserItemLikes", "verbose_name_plural": "UserItemLikes"},
        ),
        migrations.AlterModelTable(
            name="useritemlikes",
            table=None,
        ),
    ]
