# Generated by Django 4.2.13 on 2024-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_customuser_profile_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credits",
            field=models.IntegerField(default=0),
        ),
    ]
