# Generated by Django 4.2.13 on 2024-06-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_customuser_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="size_chest_inches",
        ),
    ]
