# Generated by Django 4.2.13 on 2024-06-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_remove_customer_size_chest_inches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="shoe_size_us",
        ),
    ]
