# Generated by Django 4.2.13 on 2024-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_delete_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="shoe_size_eu",
            field=models.CharField(
                blank=True,
                choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                max_length=10,
                null=True,
            ),
        ),
    ]
