# Generated by Django 4.2.13 on 2024-06-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0034_style"),
        ("accounts", "0025_alter_customer_shoe_size_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="studio_styles",
            field=models.ManyToManyField(blank=True, related_name="users_with_studio_styles", to="studio.style"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trending_mode",
            field=models.CharField(
                choices=[("discover", "Discover"), ("following", "Following")], default="discover", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trending_styles",
            field=models.ManyToManyField(blank=True, related_name="users_with_trending_styles", to="studio.style"),
        ),
    ]
