# Generated by Django 4.2.13 on 2024-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_customuser_studio_styles_customuser_trending_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritemlikes",
            name="liked_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
