# Generated by Django 4.2.13 on 2024-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_useritemlikes_liked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lifeform",
            field=models.CharField(
                choices=[("angel", "angel"), ("human", "human"), ("bot", "bot")], default="human", max_length=10
            ),
        ),
    ]
