# Generated by Django 4.2.13 on 2024-07-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_rename_invide_code_invitecode_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="studio_visibility",
            field=models.CharField(
                choices=[("discover", "Discover"), ("following", "Following")], default="discover", max_length=15
            ),
        ),
    ]
