# Generated by Django 4.2.13 on 2024-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_customuser_studio_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_change_requested_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="email change requested at"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="new_email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="new email address"),
        ),
    ]
