# Generated by Django 4.2.13 on 2024-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_customuser_email_change_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useritemcart",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useritemcart",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
