# Generated by Django 4.2.13 on 2024-08-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_useritemcart_price_useritemcart_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridPicUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gridpic_img", models.ImageField(upload_to="gridpicuploads/")),
                (
                    "gridpic_processed_img",
                    models.ImageField(blank=True, null=True, upload_to="gridpicuploads/processed/"),
                ),
                ("timedate_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "deleted_by_uploader",
                    models.CharField(choices=[("no", "no"), ("yes", "yes")], default="no", max_length=10),
                ),
                ("timedate_deleted_by_uploader", models.DateTimeField(blank=True, null=True)),
                (
                    "uploader_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
