# Generated by Django 4.2.13 on 2025-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_gridpicupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accept_private_asks",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="yes",
                help_text="Indicates if the user accepts private asks.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="private_ask_price",
            field=models.IntegerField(default=0, help_text="The price in credits for a private ask."),
        ),
    ]
