# Generated by Django 4.2.13 on 2025-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0038_alter_ecommercestore_platform"),
        ("accounts", "0035_customuser_accept_private_asks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridpicupload",
            name="gridpic_temp_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="gridpic_temp_img",
            field=models.ImageField(blank=True, null=True, upload_to="gridpicuploads/processed/temps/"),
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="gridpic_tryon_item_id",
            field=models.ManyToManyField(blank=True, to="studio.item"),
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="tryon_times",
            field=models.IntegerField(default=0),
        ),
    ]
