# Generated by Django 4.2.13 on 2025-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_gridpicupload_gridpic_temp_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gridpicupload",
            name="gridpic_temp_active",
        ),
        migrations.RemoveField(
            model_name="gridpicupload",
            name="tryon_times",
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="gridpic_tryon_img",
            field=models.ImageField(blank=True, null=True, upload_to="gridpicuploads/processed/tryons/"),
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="tryon_state",
            field=models.CharField(
                choices=[("original", "Original"), ("temp", "Temporary"), ("virtual", "Virtual")],
                default="original",
                max_length=10,
            ),
        ),
    ]
