# Generated by Django 4.2.13 on 2025-06-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0038_alter_ecommercestore_platform"),
        ("accounts", "0037_remove_gridpicupload_gridpic_temp_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gridpicupload",
            name="gridpic_tryon_item_id",
        ),
        migrations.AddField(
            model_name="gridpicupload",
            name="gridpic_tryon_item",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="studio.item"
            ),
        ),
    ]
