# Generated by Django 4.2.13 on 2025-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_link', models.URLField()),
                ('product_images', models.JSONField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_details', models.TextField()),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
