# Generated by Django 4.2.13 on 2025-07-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
