# Generated by Django 4.2.13 on 2025-07-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
