# Generated by Django 4.2.13 on 2025-07-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0004_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_main_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
