# Generated by Django 4.2.13 on 2025-07-17 18:34

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0005_product_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
