# Generated by Django 4.2.13 on 2025-07-17 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0040_item_embedding'),
        ('chatai', '0006_product_product_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_reference_outfit_id', models.IntegerField(blank=True, null=True)),
                ('chat_main_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('chat_created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_status', models.CharField(default='active', max_length=20)),
                ('chat_reference_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.item')),
                ('chat_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_is_from_user', models.BooleanField(default=True)),
                ('msg_text', models.TextField(blank=True)),
                ('msg_image', models.ImageField(blank=True, null=True, upload_to='chat_uploads/')),
                ('msg_image_url', models.URLField(blank=True, null=True)),
                ('msg_recommendations', models.JSONField(blank=True, null=True)),
                ('msg_created_at', models.DateTimeField(auto_now_add=True)),
                ('msg_message_type', models.CharField(default='text', max_length=20)),
                ('msg_chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatai.chatsession')),
            ],
        ),
    ]
