# Generated by Django 4.2.13 on 2025-07-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0007_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='chat_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
