# Generated by Django 4.2.13 on 2025-07-18 08:29

import chatai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0008_chatsession_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='chat_id',
            field=models.CharField(default=chatai.models.generate_chat_id, max_length=32),
        ),
    ]
