# Generated by Django 4.2.13 on 2025-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0009_alter_chatsession_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('top', 'top'), ('bottom', 'bottom'), ('accessory', 'accessory'), ('footwear', 'footwear'), ('dress', 'dress')], max_length=20),
        ),
    ]
